baseurl = "http://cassandra-michael-wedding.site"
languageCode = "en-us"
title = "Cassandra & Michael Wedding"
theme = "hugo-creative-theme"
googleAnalytics = ""
publishDir = "docs"

	[params]
	# Some metadata
	name = "Cassandra Bird and Michael Kearney"
	description = "Wedding Website"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = "#DoctorsKearney"

	[params.navigation.links]
		about     = "Details"
		services  = "Information"
		portfolio = "Story"
		contact   = "Contact"

	# Hero section
	[params.hero]
		slogan     = "Cassandra Bird<br>&<br>Michael Kearney"
		subtitle   = "March 24, 2018"
		buttonText = "Details"

	# About section
	[params.about]
		headline    = "Details"
		#description = "5pm (CST)<br>March 24, 2018<br>Tiger Hotel<br>Columbia, Missouri"
		time = "5:00pm (CST)"
		date = "March 24, 2018"
		venue = "Tiger Hotel"
		location = "Columbia, MO"
		buttonText  = "More information"

    	# Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

	# Service section
	[params.services]
	    headline = "Information"

        [[params.services.list]]
            icon = "fa-info"
            title = "Details"
            description = "Date, time, and location details."
	    link = "details"
	    
        [[params.services.list]]
            icon = "fa-hotel"
            title = "Hotels"
            description = "Hotel options and other lodging information in the Columbia area."
	    link = "hotels"

        [[params.services.list]]
            icon = "fa-plane"
            title = "Airlines"
            description = "Airline options (i.e., Columbia, Kansas City, St. Louis)"
	    link = "airlines"

        [[params.services.list]]
            icon = "fa-coffee"
            title = "Good eats"
            description = "Good places to eat [and Casi and Mike's recommendations] around Columbia."
	    link = "food"

    # Aside section
	[params.aside]
		headline = "Wedding Registry Links"

		[params.aside.button1]
			text = "img/target.png"
			link = "https://www.target.com/gift-registry/gift/Cassandra-Michael-Kearney"
		[params.aside.button2]
			text = "img/BBB.png"
			link = "https://www.bedbathandbeyond.com:443/store/giftregistry/view_registry_guest.jsp?registryId=544904368&eventType=Wedding&pwsurl="

	# Contact section
	[params.contact]
		headline = "Columbia, Missouri!"
		description = "The wedding will take place at <a href=\"http://www.thetigerhotel.com/\">the Tiger Hotel</a>.<br><br>23 South 8th Street<br>Columbia, MO 65201<br>United States"
		address = ""
		phone = "573-875-8888"
		email = "frontdesk@thetigerhotel.com"

	 # Google Maps section
	 [params.location]
	 	latitude  = "38.9509"
	 	longitude = "92.3288"
		maps_api_key = "AIzaSyC6OJ8_2a2uid8jMtaMweKsmzZuOET2zeo"
		#maps_api_key = "AIzaSyC6h50fCcFO3gb3XQFZ-TvJ8un8fNroQwY"
